apiVersion: apps/v1
kind: Deployment
metadata:
  name: resumebuilderbackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resumebuilderbackend
  template:
    metadata:
      labels:
        app: resumebuilderbackend
    spec:
      containers: 
      - name: resume-builder-be-k8s
        image: writerdocker/resumeai-be-jenkins-img
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
